---

version: 2

updates:

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "jkatzwinkel"
    groups:
      junit:
        patterns:
          - "org.junit.jupiter:junit-jupiter-*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "jkatzwinkel"

...
