---

name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: checkout code
      uses: actions/checkout@v3.5.2

    - name: Set up JDK 19
      uses: actions/setup-java@v3.12.0
      with:
        java-version: 19
        distribution: temurin
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

...
