---

name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 17
          - 21
          - 22

    steps:

      - name: checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4.2.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.2

      - run: java --version

      - name: Build with Gradle
        run: ./gradlew build

...
