---

name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version: [17, 21, 23]

    steps:

      - name: checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4.5.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4.2.1

      - name: Build with Gradle
        run: ./gradlew build

...
