---

name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2.0.0

      - name: Build with Gradle
        run: ./gradlew build

...
