---

name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 17
          - 21
          # - 22

    steps:

      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4.2.2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4.0.0

      - name: Build with Gradle
        run: ./gradlew build

...
