---

name: build

on:
  push:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 17
          - 21
          - 23

    steps:

      - name: checkout code @ ${{ inputs.ref || github.ref }}
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5.0.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4.4.2

      - name: Build with Gradle
        run: ./gradlew build --warning-mode all

...
